export const columns = [
    {
      title: 'First Name',
      dataIndex: 'firstName',
      key: 'firstName',
    },
    {
      title: 'Last Name',
      dataIndex: 'lastName',
      key: 'lastName',
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
    },
    {
      title: 'Gender',
      dataIndex: 'gender',
      key: 'gender',
    },
    {
        title: 'birthdate',
        dataIndex: 'birthdate',
        key: 'birthdate',
      },
    {
      title: 'address_line1',
      dataIndex: 'address_line1',
      key: 'address_line1',
    },
    {
        title: 'address_line2',
        dataIndex: 'address_line2',
        key: 'address_line2',
      },
      {
        title: 'zip',
        dataIndex: 'zip',
        key: 'zip',
      },
      {
        title: 'state',
        dataIndex: 'state',
        key: 'state',
      },
      {
        title: 'country',
        dataIndex: 'country',
        key: 'country',
      },
  ];
  
  export const data = [
    {
      key: '0',
      firstName: 'Alice',
      lastName: 'Johnson',
      age: 9,
      gender: 'F',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },
    {
      key: '1',
      firstName: 'Mike',
      lastName: 'Ford',
      age: 5,
      gender: 'M',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },
    {
      key: '2',
      firstName: 'John',
      lastName: 'Smith',
      age: 8,
      gender: 'M',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },
    {
      key: '3',
      firstName: 'Joe',
      lastName: 'Johnson',
      age: 11,
      gender: 'M',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },
    {
      key: '4',
      firstName: 'Linda',
      lastName: 'Ford',
      age: 8,
      gender: 'F',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },
    {
      key: '5',
      firstName: 'Noah',
      lastName: 'Wilson',
      age: 9,
      gender: 'M',
      birthdate: 1,
      address_line1: 4,
      address_line2: 4,
      zip: 'null',
      state: 'null',
      country: 'null',
    },

  ];